### ISSUE TITLE
Lines/Keys added to a system file are not removed

### ISSUE THREAD

**Issue by elbowz** [VorpalBlade/chezmoi_modify_manager#100]
## Describe the bug

Lines/Keys present in a system file but not in the source one (ie. src.ini), are not removed after a `chezmoi apply`

## To Reproduce

```console
% cat dot_config/modify_private_test_chmm
#!/usr/bin/env chezmoi_modify_manager

source auto

transform regex ".*" ".*" kde-shortcut
```

```console
% cat dot_config/private_test_chmm.src.ini
[Test0]
key01=value1
key02=value2
key03=value3
```

```console
% cat ~/.config/test_chmm
[Test0]
key01=value1
key02=value2
key03=value3
line_added_to_delete
```

```console
% chezmoi apply -vn
% chezmoi diff
```

Nothing is printed about  _"line_added_to_delete"_.

## Expected behavior

```diff
--- a/home/muttley/.config/test_chmm
+++ b/tmp/chezmoi-diff3590156634/.config/test_chmm
@@ -2,5 +2,4 @@
 key01=value1
 key02=value2
 key03=value3
-line_added_to_delete
````

The issue is the `transform` present in `modify_private_test_chmm`, removing it, all works.

**Comment by VorpalBlade** [comment]
That does indeed seem like a bug. My gut feeling is that it is related to the transform somehow.

**Comment by elbowz** [comment]
> That does indeed seem like a bug. My gut feeling is that it is related to the transform somehow.

Absolutely:
> The issue is the `transform` present in modify_private_test_chmm, removing it, all works.

**Comment by VorpalBlade** [comment]
A new release will be available soon
