### ISSUE TITLE
Set directive adds spaces

### ISSUE THREAD

**Issue by dgudim** [VorpalBlade/chezmoi_modify_manager#65]
## What exactly are you trying to do?

When I use the set directive, the resulting file has the key liek this:
```
key = value
```
but kde rewrites this file like this
```
key=value
```

I run chezmoi diff before every apply and this is bothering me
![image](https://github.com/VorpalBlade/chezmoi_modify_manager/assets/34401005/8da4c118-6806-4628-83d8-f6f11b6114ce)

## What have you tried so far?

```
set "Encryption" "file key" "{{ .gpg.signingkey }}"
set "Encryption" "file key" "{{- .gpg.signingkey -}}"
```

**Comment by VorpalBlade** [comment]
Hi,

There is already a way to deal with this, and that is adding the optional `separator` directive. The default is `separator=" = "` as you have discovered. However this should do what you want:

```
set "Encryption" "file key" "{{ .gpg.signingkey }}" separator="="
set "Encryption" "file key" "{{- .gpg.signingkey -}}" separator="="
```

**Comment by dgudim** [comment]
Ah, thanks, I must have skipped it in the doc.
