### ISSUE TITLE
Migrate to the new method in 3.1.0?

### ISSUE THREAD

**Issue by dgudim** [VorpalBlade/chezmoi_modify_manager#80]
## Is your feature request related to a problem? Please describe.
Reading the changelog I saw that in the latest version (3.1.0) the modify file no longer needs to be a template. I would like to migrate all my modify templates to the new system. Is there a way to do so?

## Describe the solution you'd like
Some way to migrate everything over automatically

## Describe alternatives you've considered
Converting everything manually, too tedious

**Comment by VorpalBlade** [comment]
I hadn't thought of such a way but it shouldn't be too hard in theory with a bit of shell script.

The main difficulty would be to detect if you use any other templating features in the modify scripts that would require those specific files to stay as  templates.

I have around 20 modify scripts and was planning on just doing it by hand, I'm very curious how many you have.

Either way I won't have time to look into this until at the earliest this evening, and I'm on my phone right now.

**Comment by dgudim** [comment]
No probs, take your time. I have about 30 I think. I guess I can write a script to convert them

**Comment by VorpalBlade** [comment]
The following should work, assuming you have no other templated modify scripts than those from this tool. If so you would need something a bit smarter.

```bash
# Replace all source "..." with "source auto", works even for things that remain templated
find . -iname 'modify_*.tmpl' -exec sed -i 's/source ".*"$/source auto/' {} +

# Find all modify template files that no longer contain any {{ and thus no longer needs to be templates:
find . -iname 'modify_*.tmpl' -exec grep -FL '{{' {} +
# Only do the next steps if your paths contain no spaces or other "funny" characters,
# it doesn't do proper escaping!

# Generate the move commands:
find . -iname 'modify_*.tmpl' -exec grep -FL '{{' {} + | sed 's/^\(.*\)\.tmpl$/mv \1.tmpl \1 ; /'
# Actually run them
eval "$(find . -iname 'modify_*.tmpl' -exec grep -FL '{{' {} + | sed 's/^\(.*\)\.tmpl$/mv \1.tmpl \1 ; /')"
```

**Comment by VorpalBlade** [comment]
I'll add a link to this in the release notes
